# Generated by Django 4.0.5 on 2022-12-30 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0023_alter_venta_terreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='bco_pag_com',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='palapp.bancos', verbose_name='Banco Pago Comisión'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tdoc_sun_com',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.tipodoc', verbose_name='Doctumento Pago Comisión'),
        ),
    ]
