# Generated by Django 4.0.5 on 2022-11-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0014_alter_terreno_mlder_alter_terreno_mlfondo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['appat', 'apmat', 'nomb']},
        ),
        migrations.AlterModelOptions(
            name='terreno',
            options={'ordering': ['manzana', 'lote'], 'verbose_name': 'terreno', 'verbose_name_plural': 'terrenos'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['appat', 'apmat', 'nomb']},
        ),
        migrations.AddField(
            model_name='venta',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='foto_contrato',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto Voucher'),
        ),
        migrations.AddField(
            model_name='venta',
            name='plan_generado',
            field=models.BooleanField(default=False, verbose_name='Plan de Pago Generado'),
        ),
    ]
