# Generated by Django 4.0.5 on 2022-11-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0015_alter_cliente_options_alter_terreno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='condvta',
            field=models.CharField(choices=[('C', 'Contado'), ('B', 'Financ.Banco'), ('P', 'FInanc.Propio Efectivo'), ('L', 'FInanc.Propio Efectivo')], default='C', max_length=1, verbose_name='Condición Venta'),
        ),
    ]
