# Generated by Django 4.0.5 on 2022-11-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0016_alter_venta_condvta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmobiliaria',
            name='fecha_act',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.venta', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='condvta',
            field=models.CharField(choices=[('C', 'Contado'), ('B', 'Financ.Banco'), ('P', 'FInanc.Propio Efectivo'), ('L', 'FInanc.Propio Letras')], default='C', max_length=1, verbose_name='Condición Venta'),
        ),
    ]
