# Generated by Django 4.0.5 on 2022-12-13 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0018_venta_cuotas_venta_fecha_1ervct_venta_fecha_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmobiliaria',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 13, 56, 8, 891607)),
        ),
        migrations.AlterField(
            model_name='inmobiliaria',
            name='fecha_inicon',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 18, 56, 8, 890608, tzinfo=utc), verbose_name='Fecha Inicio de Contrato'),
        ),
    ]
