# Generated by Django 4.0.5 on 2022-12-30 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0022_bancos_tipodoc_cliente_feccad_venta_com_pag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='terreno',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='palapp.terreno', verbose_name='Terreno'),
        ),
    ]
