# Generated by Django 4.0.5 on 2023-01-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0023_alter_venta_terreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='bco_pag_com',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='palapp.bancos', verbose_name='Banco Pago Comisión'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tdoc_sun_com',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='palapp.tipodoc', verbose_name='Doctumento Pago Comisión'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, default=' ', max_length=8, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ocupación'),
        ),
    ]
