# Generated by Django 4.0.5 on 2023-01-16 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palapp', '0025_venta_doc_cotitular_venta_nom_cotitular_venta_y_o'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='usuario_crea',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Coordinador'),
        ),
        migrations.AddField(
            model_name='tipodoc',
            name='usuario_crea',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Coordinador'),
        ),
    ]
