# Generated by Django 2.2.13 on 2023-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0028_venta_d_contrato_alter_cliente_apmat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='d_contrato',
            field=models.FileField(blank=True, default='', upload_to='media/', verbose_name='Doc.Escaneado'),
        ),
    ]
