# Generated by Django 4.1.3 on 2023-02-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0028_alter_cliente_apmat'),
        ('palapp', '0028_venta_d_contrato_alter_cliente_apmat'),
    ]

    operations = [
    ]
