# Generated by Django 4.1.3 on 2023-03-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palapp', '0029_auto_20230301_0935'),
        ('palapp', '0029_merge_20230228_1121'),
    ]

    operations = [
    ]
